version: "3.3"

services:

  web:
    build: ./flask
    container_name: flask
    image: bplus_flask
    restart: always
    environment:
      - APP_NAME=BFlaskAPP
    expose:
      - "8080"
    volumes:
      - /app/web
    command:
      /usr/local/bin/gunicorn wsgi:app -w 2 -t 90 --log-level=debug -b 0.0.0.0:8080 --reload

  nginx:
    build: ./nginx
    container_name: nginx
    image: bplus_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    tty: true
