version: "3.3"

services:

  flask:
    build: ./flask
    container_name: flask
    image: bplus_flask
    #restart: always
    environment:
      - APP_NAME=BFlaskAPP
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    image: bplus_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
